# configuration variables
CSV_TA_NETHZ = 'ta_nethz'
CSV_LECTURE_NAME = 'lecture_name'
SQL_INITIALIZATION_FILE = '../SQL/SQLDatabaseCreationFile.txt'
SECRET = "V3RySup3rs3Cr3t"
_RATING_NUMBER_OF_OPTIONS = 5
RATING_SCALE_FACTOR = 100/_RATING_NUMBER_OF_OPTIONS
